### ISSUE TITLE
Limitation error

### ISSUE THREAD

**Issue by jchuerva** [christopher-dG/markdown-tables#1]
👋  @christopher-dG 

I'm using your gem to generate a huge table with `columns = 8-10` and `row = 69` and I have the issue:
```
RuntimeError: Too many data columns given
from /Users/jchuerva/.rvm/gems/ruby-2.4.1/gems/markdown-tables-1.0.1/lib/markdown-tables.rb:99:in `validate'
```

Is there any limitation in the number of columns or rows?

thanks!

**Comment by christopher-dG** [comment]
Oh boy, haven't looked at this code in a long time... 

There isn't supposed to be.

It looks like you are leaving `is_rows` as `false`. Are you passing your data as a list of rows maybe? The code path that triggers that error is: `!is_rows && data.length > labels.length`, so I'm pretty sure if you want to generate this:

|title1|title2|
|:-:|:-:|
|x|y|
|a|b|
|a|z|

You should pass data as `[['x', 'y', 'a'], ['y', 'b', 'z']]`

I'm not completely sure if that's the case or if there's a bug, I can take a closer look tonight.

**Comment by christopher-dG** [comment]
Okay I was able to reproduce the error with the situation I described above, if that isn't what you're doing then let me know how you're callng it and I can investigate further.

**Comment by jchuerva** [comment]
yeah @christopher-dG !! I forgot `is_rows: true`

thanks a lot for your help!!
